# Dockerfile

FROM ruby:3.1.3-slim
# Install apt based dependencies required to run Rails as
# well as RubyGems. As the Ruby image itself is based on a
# Debian image, we use apt-get to install those.

RUN apt-get update && apt-get install -y \
  build-essential \
  nano \
  nodejs \
  libpq-dev \
  postgresql-client \ 
  curl

RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get install -y nodejs

RUN mkdir -p /app
WORKDIR /app

# Copy the Gemfile as well as the Gemfile.lock and install
# the RubyGems. This is a separate step so the dependencies
# will be cached unless changes to one of those two files
# are made.

COPY Gemfile* ./

RUN bundle install

RUN gem install foreman

COPY . /app

RUN rm -rf tmp/*

ADD . /app
