# docker-compose.yml

version: "3.8"
networks:
  backend:


services:
  client:
    image: nginx:latest
    ports:
      - "5173:80"
    volumes:
      - ./public/client/:/usr/share/nginx/html
      - ./client-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - backend

  app:
    build:
      dockerfile: Dockerfile.development
    tty: true
    volumes:
      - .:/app
    working_dir: /app
    environment:
      REDIS_URL: redis://redis:6379
      RAILS_ENV: development
    command: [ "./bin/start", "rails", "server", "-b", "0.0.0.0", "-p", "3000" ]
    networks:
      - backend
    ports:
      - "3000:3000"
    depends_on:
      - redis
volumes:
  archive_box:
